apiVersion: v1
kind: Pod
metadata:
  name: team-volume-pod
spec:
  containers:
    - name: test-container
      image: busybox:1.34
      command:
      - sleep
      - "3600"
      volumeMounts:
      - name: team-volume
        mountPath: /data/team-members
  volumes:
    - name: team-volume
      configMap:
        name: users-cm
