apiVersion: v1
kind: Pod
metadata:
  name: team-pod
spec:
  containers:
    - name: test-container
      image: busybox:1.34
      command:
      - sleep
      - "4800"
      envFrom:
      - configMapRef:
          name: users-cm
