apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rival
  name: rival
  namespace: task-5
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rival
  template:
    metadata:
      labels:
        app: rival
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app-server
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rival
              topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - image: 8s.gcr.io/pause:3.3
        name: maink
