apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exercise
  name: exercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise
  template:
    metadata:
      labels:
        app: exercise
    spec:
      containers:
      - image: k8s.gcr.io/pause:3.3
        name: main
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "production"
        effect: "NoSchedule"
