apiVersion: v1
kind: Pod
metadata:
  name: corporate-app
  namespace: default
spec:
  containers:
  - image: registry.gitlab.com/playpit-labs/images/blackbox:v3.3
    name: corporate-app
  serviceAccount: private-registry
  serviceAccountName: private-registry
