apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-with-sc
  labels:
    pvc: 2gbi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: playpit-labs-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-st-cl
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  flexVolume:
    driver: hpe.com/nimble
  storageClassName: playpit-labs-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: testing-pvc-sc
spec:
  containers:
  - image: busybox:1.34
    name: container-a
    command:
      - sleep
      - infinity
    volumeMounts:
    - name: volume-with-sc
      mountPath: /data
  volumes:
    - name: volume-with-sc
      persistentVolumeClaim:
        claimName: pvc-with-sc
