apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    application: scapegoat
  name: scapegoat
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      application: scapegoat
  template:
    metadata:
      annotations:
        app.kubernetes.io/component: main
        app.kubernetes.io/name: scapegoat
        app.kubernetes.io/owned_by: Siarhei Beliakou
        app.kubernetes.io/uuid: e6eddb36-a6ee-4336-a43d-4a88a6409b69
        app.kubernetes.io/version: v1.01
      creationTimestamp: null
      labels:
        application: scapegoat
        chargecode: "12345"
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: busybox:1.34
        name: main
        resources:
          limits:
            cpu: 250m
            memory: 64Mi
          requests:
            cpu: 125m
            memory: 32Mi
        env:
          - name: CPU_REQUEST
            valueFrom:
              resourceFieldRef:
                containerName: main
                resource: requests.cpu
          - name: CPU_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: main
                resource: limits.cpu
          - name: RAM_REQUEST
            valueFrom:
              resourceFieldRef:
                containerName: main
                resource: requests.memory
          - name: RAM_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: main
                resource: limits.memory
        volumeMounts:
        - name: podinfo
          mountPath: /podinfo
      volumes:
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
