apiVersion: v1
kind: Pod
metadata:
  name: web-tricky-pod-emptydir
  labels:
    app: MyApp
spec:
  initContainers:
  - image: busybox:1.34
    name: init-contanier-1
    command:
      - /bin/sh
      - -c
      - |
       cat << EOF > /html/index.html
       <html>
         <head></head>
         <body>
           <b>Student</b>: Aleksei Kuzmin1<br>
           <b>pod name</b>: $(hostname)<br>
           <b>pod ip</b>: $(hostname -i)<br>
         </body>
       </html>
       EOF
    volumeMounts:
    - mountPath: /html
      name: shared-pod-volume

  containers:
  - image: nginx:alpine
    name: container-a
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-pod-volume

  volumes:
  - name: shared-pod-volume
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-tricky-pod-emptydir-svc
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
