apiVersion: v1
kind: Pod
metadata:
  name: dev-volume-pod
spec:
  containers:
    - name: test-container
      image: busybox:1.34
      command:
      - sleep
      - "3600"
      volumeMounts:
      - name: devops-volume
        mountPath: /data/devops-secret
  volumes:
    - name: devops-volume
      secret:
        secretName: devops-secret
