apiVersion: v1
kind: Pod
metadata:
  name: email-pod
spec:
  containers:
    - name: test-container
      image: busybox:1.34
      command:
      - sleep
      - "4800"
      env:
        # Define the environment variable
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              # The Secret containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: devops-secret
              # Specify the key associated with the value
              key: email
